### ISSUE TITLE
Initial bazel-diff run is resource hungry and time intensive

### ISSUE THREAD

**Issue by mattboardman** [Tinder/bazel-diff#54] opened 2021-02-02 23:30 UTC
I build my projects using Jenkins pipeline jobs executed in fresh containers. Running the bazel-diff tool on a fresh clone of the repo can take an incredibly long time, even when there are 4 cores and 8gb of memory available. Subsequent runs are much faster (almost instantaneous).

Some questions:

* Is this normal behavior? 
* what are the benchmarks for bazel-diff?
* Is there anything I can do to speed up execution?
* If work is required on the tool itself, what features need to be worked on? I'd love to contribute if possible. 

Thanks

**Comment by tinder-maxwellelliott** [comment] 2021-02-03 18:50
> Is this normal behavior?

This does not sound like expected behavior, I would expect a run to take minutes at max on a massive repository. Can you try running the example script using the verbose flag enabled to give more insight? https://github.com/Tinder/bazel-diff/blob/master/bazel-diff-example.sh#L22

> what are the benchmarks for bazel-diff?

I can work on creating test harnesses for this. For our repository we can run in order of seconds

> Is there anything I can do to speed up execution?

See answer to first question, I need to see verbose output to understand what is causing this delay

> If work is required on the tool itself, what features need to be worked on? I'd love to contribute if possible.

Sounds great

**Comment by mattboardman** [comment] 2021-02-03 19:55
I cloned the bazel-diff repo and ran the script with the verbose flag on my workspace after I performed a `bazel clean --expunge`. I touched a single BUILD file target between the two commits and nothing else. 

The script hung on the rdeps query for >25 minutes (I did not wait to see if it would ever finish)
```
[matt@quadro bazel-diff]$ ./bazel-diff-example.sh /home/matt/workspace/meb_life/ $(which bazel) a671534a1c25cc7220de110470d0fe473049fe41 dfddb16ffaa466a8040baee31bf8d7894f5d90e1
INFO: Build completed successfully, 1 total action
Modified Filepaths:
packages/alexjboardman/BUILD.bazel

Generating Hashes for Revision 'a671534a1c25cc7220de110470d0fe473049fe41'
Executing Query: '//external:all-targets' + '//...:all-targets'
Generating Hashes for Revision 'dfddb16ffaa466a8040baee31bf8d7894f5d90e1'
Executing Query: 'packages/alexjboardman/BUILD.bazel'
Executing Query: '//external:all-targets' + '//...:all-targets'
Determining Impacted Targets
Executing Query: rdeps(//..., '//packages/alexjboardman:copy_templates' + '//packages/alexjboardman:image' + '//packages/alexjboardman:flask' + '//packages/alexjboardman:app' + '//packages/alexjboardman:pack_static_files' + '//packages/alexjboardman:dev.resolve' + '//packages/alexjboardman:dev.delete' + '//packages/alexjboardman:copy_static_files' + '//packages/alexjboardman:dev.replace' + '//packages/alexjboardman:dev.apply' + '//packages/alexjboardman:pack_templates' + '//packages/alexjboardman:dev' + '//packages/alexjboardman:BUILD.bazel' + '//packages/alexjboardman:image.binary' + '//packages/alexjboardman:dev.describe' + '//packages/alexjboardman:dev.create')
```

**Comment by BalestraPatrick** [comment] 2021-02-08 14:20
I'm seeing exactly the same issue. The first time it runs on any of our build agents it takes a long time to complete the `Determining Impacted Targets` step. For me it took almost 5 minutes to complete. After this, `Determining Test Targets` is much faster.

**Comment by tinder-maxwellelliott** [comment] 2021-02-09 17:49
I have some optimizations planned for this and am working on a branch now locally, I hypothesize that in our `rdeps` call we should exclude all external targets since obviously you have no control over those targets

**Comment by tinder-maxwellelliott** [comment] 2021-02-09 18:03
Can anybody experiment with this branch and see if it helps? maxwelle/optimize_rdeps

It looks like `rdeps` is the culprit here, in that branch I am trying to optimize it by reducing its search scope

**Comment by mattboardman** [comment] 2021-02-09 18:10
I can try it later today and get back to you.

**Comment by tinder-maxwellelliott** [comment] 2021-03-04 17:18
I merged #55 , Can you try with that and let me know if performance is any better?

**Comment by mattboardman** [comment] 2021-03-04 17:22
Ah I never got back to you! Yes this improved performance thanks for the quick turn around.

**Comment by tinder-maxwellelliott** [comment] 2021-03-04 17:48
Is it safe to close this for now? Or are you facing issues still?

**Comment by mattboardman** [comment] 2021-03-04 17:48
We can close this. Thank you!

**Closed** 2021-03-04 18:58 UTC
